### ISSUE TITLE
Unclear symbol

### ISSUE THREAD

**Issue by antosha417** [amkatrutsa/MIPT-Opt#23]
In lecture 6 slide 6  last line, how should I understand symbol \bI?
![image](https://user-images.githubusercontent.com/14187674/31556474-e08b4026-b04d-11e7-85a8-5675b2371bf6.png)

**Comment by antosha417** [comment]
Is it vector of all ones?

**Comment by amkatrutsa** [comment]
This is the standard notation of the identity matrix.
